//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiShop.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtributePrice
    {
        public int AtributePriceID { get; set; }
        public Nullable<int> AtributeID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Atribute Atribute { get; set; }
        public virtual Product Product { get; set; }
    }
}
