//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiShop.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipper
    {
        public int ShipID { get; set; }
        public string ShiperName { get; set; }
        public string Phone { get; set; }
        public string Company { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
    }
}
