//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiShop.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinTuc
    {
        public int PostID { get; set; }
        public string Titile { get; set; }
        public string SContens { get; set; }
        public string Contents { get; set; }
        public string Thumbs { get; set; }
        public bool Published { get; set; }
        public string Alias { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Author { get; set; }
        public Nullable<int> AccountID { get; set; }
        public string Tags { get; set; }
        public Nullable<int> CateID { get; set; }
        public Nullable<bool> isHot { get; set; }
        public Nullable<bool> isNewfeed { get; set; }
        public string MetaDes { get; set; }
        public string MeteKey { get; set; }
        public Nullable<int> Views { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Category Category { get; set; }
    }
}
